### ISSUE TITLE
unity install from git have many compile error

### ISSUE THREAD

**Issue by mjfme** [Chillu1/ModiBuff#46]
**Describe the bug**
![image](https://github.com/user-attachments/assets/9ef730d6-a11a-42b3-965c-783ba262192b)

**To Reproduce**
uniy 2022.3 , just install from the url https://github.com/Chillu1/ModiBuff.git#upm with package manager

Am I missing any setup configurations or version requirements?

**Expected behavior**

**Comment by mjfme** [comment]
Thank you for your reply.
> You can import the library manually by copying over the ModiBuff/ModiBuff directory to something like a plugins directory for now.

I have try this way already. I put ModiBuff.Core and ModiBuff.Units to my project . Basically I can try to learn to use Modibuff now. But there is a problem with json serialization related functionality, unity not support for .net native System.Text.Json, here are some [infomation](https://discussions.unity.com/t/please-add-system-text-json-support/815652)

**Comment by Chillu1** [comment]
Yeah sorry, that's on me. The serialization logic should be split into two parts, one generic where it doesn't have an opinion on the the serialization implementation.

And the other that uses `System.Text.Json`, I still haven't encapsulated that logic in a compiler directive `MODIBUFF_JSON...`.

It's a thing currently with the master branch, should have made a separate branch for it instead, sorry. Will fix that code in the weekend.

**Comment by Chillu1** [comment]
`System.Text.Json` is fixed in master branch, haven't touched/looked into the upm/Unity thing yet. But regenerating the meta files/downloading the source manually should work just fine.

**Comment by mjfme** [comment]
cool! you are right , I add missing .meta files ,  everything work OK .
