### ISSUE TITLE
Remove multiple modifiers at the same time cause NullReferenceException,modifier will not removed , in unity

### ISSUE THREAD

**Issue by Strongweak** [Chillu1/ModiBuff#55]
**Describe the bug**
I have hand imported the API to Unity, this appear when 2 or more modifier remove at the same time, the modifier will not be removed.

**To Reproduce**
1. Create 2 recipes Effect1 and Effect2, both using with Remove, Refresh, Revert.
2. Call and use Effect1 and Effect2 at the same time or Effect2 slightly before Effect1.

**Expected behavior**
An error will appear in the console
NullReferenceException: Object reference not set to an instance of an object
ModiBuff.Core.ModifierPool.Return (ModiBuff.Core.Modifier modifier)

The line in Error point to: modifier.ResetState();

[ModiBuff] Tried to remove a modifier that doesn't exist on entity, id: 2, genId: 63

**Comment by Chillu1** [comment]
I can't recreate it, think I might be missing a step/something.

By call and use, you mean adding and trigger the effect, correct? Also, are you removing the modifiers on set duration or on init? The latter might be unintended, but should still work normally.

This passes:

```cs
[Test]
public void TwoEffectSameDurationRemove()
{
    AddRecipe("DurationAddDamageRemove")
        .Effect(new AddDamageEffect(1, EffectState.IsRevertible), EffectOn.Init)
        .Remove(5).Refresh();
    AddRecipe("DurationAddDamageRemove2")
        .Effect(new AddDamageEffect(2, EffectState.IsRevertible), EffectOn.Init)
        .Remove(5).Refresh();
    Setup();

    Unit.AddModifierSelf("DurationAddDamageRemove2");

    Unit.Update(0.01f);

    Unit.AddModifierSelf("DurationAddDamageRemove");
    Unit.Update(0f);

    Assert.AreEqual(UnitDamage + 1 + 2, Unit.Damage);

    for (int i = 0; i < 51; i++)
        Unit.Update(0.1f);

    Assert.False(Unit.ContainsModifier("DurationAddDamageRemove"));
    Assert.False(Unit.ContainsModifier("DurationAddDamageRemove2"));
    Assert.AreEqual(UnitDamage, Unit.Damage);
}
```

Could you copy your recipes code, and describe on how and when you trigger each action (effect trigger, remove)?

**Comment by Chillu1** [comment]
Think I found it, are you by any chance on an older version than 2d634423b9f2f426b23d873ae802a3b13fb097a8?

It fixed a bug with removing a modifier from the top of the stack.

**Comment by Strongweak** [comment]
Thank you so much, it true that they have imported the older version (about last year), after copy the commit change code, it work perfectly.
