### ISSUE TITLE
How to actually use Callback ?

### ISSUE THREAD

**Issue by Strongweak** [Chillu1/ModiBuff#56]
**Logic description**
i try to make stun effect that remove over time or remove if victim getting hit
        Add("Stun", "Cannot attack or move for n seconds, or break out if getting hit")
            .Effect(new StunEffect(true), EffectOn.Init)
            .Remove(5f)
            .Remove(RemoveEffectOn.CallbackUnit)
            .CallbackUnit(CallbackType.StrongHit)
            .Refresh();
In the document show how to implement Callback
ICallbackUnitRegistrable.RegisterCallbacks(TCallbackUnit, IEffect[]).
but i doesnt understand how to implement to the unit, even in the example doesnt have example related to Callback.

**Comment by Chillu1** [comment]
Yeah, I should explain the logic a bit better in the readme.

Essentially the unit itself should hold these registered callbacks, one way or another, doesn't matter if you chose a list, array, C# event actions, etc.

Your Unit implementation needs to inherit [ICallbackUnitRegistrable](https://github.com/Chillu1/ModiBuff/blob/master/ModiBuff/ModiBuff/Core/Unit/ICallbackUnitRegistrable.cs)

ModiBuff.Units shows how it implement it.
In that implementation, you should add & remove the callbacks to/from the Unit like [here](https://github.com/Chillu1/ModiBuff/blob/master/ModiBuff/ModiBuff.Units/Unit/UnitCallbacks.cs#L129)

Then in your TakeDamage function you should iterate through all the callbacks and call them like [here](https://github.com/Chillu1/ModiBuff/blob/master/ModiBuff/ModiBuff.Units/Unit/Unit.cs#L264)

The unit implementation is huge so it shows almost all that's possible to do with the library. But maybe I should add some basic examples/info on this in the ReadMe as well, will think about it.
